# Generated by cucumber-sinatra. (2015-01-09 15:38:59 +0000)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rps_game.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = RPSgame

class RPSgameWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  RPSgameWorld.new
end
